# Generated by Django 6.0.5 on 2026-05-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_otpverification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpverification",
            name="expires_at",
            field=models.DateTimeField(),
        ),
    ]
