# Generated by Django 6.0.5 on 2026-05-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_otpverification_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="banner_image",
            field=models.ImageField(blank=True, null=True, upload_to="banners/"),
        ),
        migrations.AddField(
            model_name="user",
            name="headline",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
