# Generated by Django 6.0.5 on 2026-06-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_banner_image_user_headline_user_is_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cancelled_sessions",
            field=models.IntegerField(default=0),
        ),
    ]
