# Generated by Django 6.0.5 on 2026-06-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_cancelled_sessions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="cancelled_sessions",
        ),
        migrations.AddField(
            model_name="profile",
            name="cancelled_sessions",
            field=models.IntegerField(default=0),
        ),
    ]
