# Generated by Django 6.0.5 on 2026-06-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_user_cancelled_sessions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="reliability_score",
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
    ]
