# Generated by Django 6.0.5 on 2026-06-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_profile_reliability_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="reliability_score",
        ),
    ]
