# Generated by Django 6.0.5 on 2026-05-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill_sessions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionrequest",
            name="completed_by_receiver",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sessionrequest",
            name="completed_by_sender",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sessionrequest",
            name="meeting_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sessionrequest",
            name="meeting_link_added_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
