# Generated by Django 6.0.5 on 2026-06-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skill_sessions", "0002_sessionrequest_completed_by_receiver_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionrequest",
            name="session_ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sessionrequest",
            name="session_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
